---

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8012/eureka/

---

spring:
  profiles: noun
words: icicle,refrigerator,blizzard,snowball

---

spring:
  profiles: default
words: boat,book,vote,seat,backpack,partition,groundhog

---

spring:
  profiles: verb
words: ran,knew,had,saw,bought

---

spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely
 
 ---
 
spring: 
  profiles: article
words: a,the

---
