---

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/

---

zuul:
  routes:
    frontend-service:
      path: /**
    article-service:
      path: /services/article-service/**
    noun-service:
      path: /services/noun-service/**
    adjective-service:
      path: /services/adjective-service/**

---

spring:
  profiles: noun
  application:
    name: noun-service
words: icicle,refrigerator,blizzard,snowball
eureka:
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

---

spring:
  profiles: noun-secondary
  application:
    name: noun-service
words: boat,book,vote,seat,backpack,partition,groundhog
eureka:
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

---

spring:
  profiles: verb
  application:
    name: verb-service
words: ran,knew,had,saw,bought

---

spring:
  profiles: adjective
  application:
    name: adjective-service
words: reasonable,leaky,suspicious,ordinary,unlikely
 
---
 
spring: 
  profiles: article
  application:
    name: article-service
words: a,the

---

spring: 
  profiles: subject
  application:
    name: subject-service
words: I,You,He,She,It

---

spring: 
  profiles: sentence
  application:
    name: sentence-service
wordConfig:
  lucky-word: Cruicial
  preamble: The lucky word is
  
---
